/**
 * Veritabanı hatalarını kullanıcıya gösterilecek Türkçe mesajlara çevirir.
 * SQL fonksiyonları `RAISE EXCEPTION '<kod>'` ile kısa kodlar atar; kısıt ihlalleri
 * Postgres'in standart mesajını taşır. Teknik ayrıntı (SQL mesajı, tablo adı) kullanıcıya ASLA gösterilmez.
 */
const KOD_MESAJLARI: Record<string, string> = {
  isletme_yok: "Hesabınız bir işletmeye bağlı değil.",
  yetki_yetersiz: "Bu işlem için yetkiniz yok.",
  musteri_bulunamadi: "Müşteri bulunamadı.",
  paket_bulunamadi: "Paket bulunamadı.",
  uyelik_bulunamadi: "Üyelik bulunamadı.",
  giris_bulunamadi: "Giriş kaydı bulunamadı veya zaten iptal edilmiş.",
  giris_iptal_suresi_doldu: "Giriş kaydı yalnızca aynı gün içinde iptal edilebilir.",
  veli_gerekli: "18 yaş altı müşteri için veli bilgisi (ad ve telefon) zorunludur.",
  veli_onayi_gerekli: "18 yaş altı müşteri için veli onayı zorunludur.",
  saglik_riza_gerekli: "Sağlık bilgisi kaydetmek için açık rıza onayı gerekir.",
  paket_satisa_kapali: "Bu paket satışa kapalı.",
  gecmis_baslangic: "Başlangıç tarihi bugünden önce olamaz.",
  iskonto_asildi: "İskonto paket fiyatını aşamaz.",
  odeme_asildi: "Ödeme, iskonto sonrası tutarı aşamaz.",
  odeme_yontemi_gerekli: "Ödeme yöntemi seçin.",
  dondurma_izni_yok: "Bu üyelik dondurulamaz.",
  dondurma_gun_gecersiz: "Dondurma gün sayısı en az 1 olmalı.",
  dondurma_uygun_degil: "Üyelik şu an dondurulamaz (aktif olmalı ve bitiş tarihi olmalı).",
  dondurma_limiti: "Dondurma hakkı yetersiz.",
  dondurma_cakisma: "Bu tarihlerde zaten bir dondurma var.",
  aktif_dondurma_yok: "Aktif bir dondurma bulunamadı.",
  iade_icin_odeme_gerekli: "İade bir ödemeye bağlı olmalıdır.",
  iade_musteri_uyumsuz: "İade, ödemeyi yapan müşteriye yapılmalıdır.",
  iade_tutari_asildi: "İade tutarı ödeme tutarını aşamaz.",
  defter_degismez: "Cari kayıtları değiştirilemez; düzeltme için yeni kayıt girin.",
  degismez_alan: "Bu alan değiştirilemez.",
  isletme_degistirilemez: "Kullanıcının işletmesi değiştirilemez.",
  antrenor_dolu: "Antrenörün bu saatte başka bir dersi var.",
  alan_dolu: "Bu alan/stüdyo bu saatte dolu.",
  musteri_dolu: "Müşterinin bu saatte başka bir dersi var.",
  cakisma: "Bu saatte çakışan bir ders var.",
  sure_gecersiz: "Ders süresi 15-480 dakika olmalı.",
  ucret_gecersiz: "Ders ücreti geçersiz.",
  antrenor_bulunamadi: "Antrenör bulunamadı veya pasif.",
  alan_bulunamadi: "Alan/stüdyo bulunamadı veya pasif.",
  ders_bulunamadi: "Ders bulunamadı.",
  gecmis_tarih: "Tercih edilen tarih bugünden önce olamaz.",
  pozisyon_personel_bagli: "Bu pozisyonda hâlâ aktif personel var; önce onları başka bir pozisyona taşıyın.",
  pozisyon_atanamaz: "Seçilen pozisyon aktif değil veya sistem erişimi kapalı.",
  pozisyon_rol_uyumsuz: "Personelin rolü pozisyonun rolüyle uyuşmuyor.",
  pozisyon_bulunamadi: "Pozisyon bulunamadı.",
  talep_bulunamadi: "Talep bulunamadı veya zaten sonuçlandırılmış.",
  yorum_turu_gecersiz: "Geçersiz yorum türü.",
  puan_gecersiz: "Puan 1 ile 5 arasında olmalı.",
  yorum_gerekli: "Yorum metnini yazın.",
  yorum_icin_katilim_gerekli: "Yorum yalnızca müşterinin katıldığı ders için yazılabilir.",
  ders_tasinamaz: "Yalnızca planlanmış veya ertelenmiş dersler taşınabilir.",
  gecersiz_durum: "Geçersiz ders durumu.",
  gecikme_gerekli: "Gecikme süresini (dakika) girin.",
  tarih_araligi_gecersiz: "Tarih aralığı geçersiz.",
  tarih_araligi_cok_uzun: "Tarih aralığı en fazla 1 yıl olabilir.",
  izin_tipi_gecersiz: "İzin türü geçersiz.",
  izin_gun_yok: "Seçilen aralıkta iş günü yok (Pazar ve resmi tatiller sayılmaz).",
  gecmis_izin: "Bu izin için geçmiş bir tarih seçilemez.",
  izin_bakiyesi_yetersiz: "Yıllık izin bakiyesi yetersiz.",
  izin_cakisma: "Bu tarihlerde zaten bekleyen veya onaylı bir izin var.",
  izin_bulunamadi: "İzin talebi bulunamadı.",
  izin_durumu_uygun_degil: "Bu izin talebi için bu işlem yapılamaz.",
  red_gerekce_gerekli: "Reddetmek için gerekçe yazın.",
  antrenor_izinli: "Antrenör bu tarihte izinli; başka bir gün veya antrenör seçin.",
  banka_hesabi_bulunamadi: "Banka hesabı bulunamadı veya pasif.",
  kategori_uygun_degil: "Bu kategori seçilen gider türüyle uyumlu değil.",
  donem_gerekli: "Kamu ödemesi için ait olduğu dönemi (ay ve yıl) seçin.",
  risk_zaten_var: "Bu türde aktif bir risk bayrağı zaten var; önce kaldırın.",
  risk_bulunamadi: "Risk bayrağı bulunamadı veya zaten kaldırılmış.",
  iban_gecersiz: "Geçerli bir TR IBAN girin.",
  muhasebe_bilgi_eksik: "Client ID ve Şirket (Company) ID gerekli.",
  arac_bulunamadi: "Araç bulunamadı veya pasif.",
  gelecek_tarih: "Tarih bugünden sonra olamaz.",
  bekleyen_gider_yontem_olmaz: "Bekleyen giderde ödeme yöntemi seçilmez.",
  gider_bulunamadi: "Gider kaydı bulunamadı.",
  gider_durumu_uygun_degil: "Bu gider için bu işlem yapılamaz.",
  iptal_nedeni_gerekli: "İptal nedenini yazın.",
  hareket_secilmedi: "En az bir borç satırı seçin.",
  hareket_gecersiz: "Seçilen satırlardan biri faturalanamaz (borç değil ya da tutarı sıfır).",
  fatura_bilgisi_eksik: "Müşterinin fatura bilgileri (e-posta, T.C. kimlik no, adres) eksik; önce tamamlayın.",
  eposta_gecersiz: "Geçerli bir e-posta adresi girin.",
  tc_gecersiz: "Geçerli bir T.C. kimlik numarası girin.",
  birden_fazla_musteri: "Bir fatura yalnızca tek müşterinin borçlarını içerebilir.",
  zaten_faturalanmis: "Seçilen borçlardan biri zaten faturalanmış.",
  fatura_bulunamadi: "Fatura bulunamadı.",
  fatura_durumu_uygun_degil: "Bu fatura için bu işlem yapılamaz (kesilmiş faturalar buradan iptal edilemez).",
  donem_bitmedi: "Dönem henüz bitmedi; yalnızca biten aylar kapatılabilir.",
  hareket_turu_gecersiz: "Geçersiz hareket kategorisi.",
  tarih_gelecek: "Tarih bugünden ileri olamaz.",
  tutar_gecersiz: "Tutar sıfırdan büyük olmalı.",
  dogum_tarihi_gecersiz: "Doğum tarihi geçerli bir geçmiş tarih olmalı.",
  acil_kisi_eksik: "Acil durum kişisi için ad ve telefon birlikte girilmelidir.",
  belge_bulunamadi: "Belge bulunamadı veya zaten kaldırılmış.",
  basvuru_bulunamadi: "Başvuru bulunamadı veya zaten sonuçlanmış.",
  puantaj_donem_kapali: "Bu ayın hakedişi kapatılmış; puantaj değiştirilemez.",
  puantaj_izinli_gun: "Personel bu gün onaylı izinde; puantaj izin kaydından türetilir.",
  personel_bulunamadi: "Personel bulunamadı.",
  puantaj_hizli_gecersiz: "Giriş/çıkış ve saat geçerli olmalı.",
  puantaj_giris_var: "Bugün için giriş zaten kaydedilmiş.",
  puantaj_cikis_var: "Bugün için çıkış zaten kaydedilmiş.",
  puantaj_giris_yok: "Önce giriş kaydedilmeli.",
  puantaj_saat_gecersiz: "Çıkış saati giriş saatinden sonra olmalı.",
  borc_islendi: "Bu ders için cariye borç yazıldı; durumu geri alınamaz. Düzeltme gerekiyorsa cari üzerinden yapın.",
};

/** Kısıt/izin ihlalleri için ipuçları (Postgres standart mesajından). */
const IPUCLARI: Array<[RegExp, string]> = [
  [/row-level security|permission denied/i, "Bu işlem için yetkiniz yok."],
  [/musteri_telefon_check|telefon.*check/i, "Telefon numarası geçerli değil."],
  [/tc_kimlik/i, "T.C. kimlik numarası geçerli değil."],
  [/profil_tarih_kurali/i, "İşten çıkış tarihi işe girişten önce olamaz."],
  [/kbh_hesap_xor|kbh_hedef_kurali|kbh_farkli/i, "Hesap seçimi geçersiz: kasa veya bir banka hesabı seçin; transferde kaynak ve hedef farklı olmalı."],
  [/hareket_banka_kurali|gider_banka_kurali|phh_banka_kurali/i, "Banka hesabı yalnız havale veya kredi kartı ile seçilebilir."],
  [/paket_tur_kurali|paket_dondurma_kurali/i, "Paket bilgileri tutarsız: tür, süre/seans ve dondurma alanlarını kontrol edin."],
  [/hareket_yontem_kurali/i, "Ödeme yöntemi eksik veya hatalı."],
  [/hareket_iskonto_kurali/i, "İskonto tutardan büyük olamaz."],
  [/duplicate key|unique/i, "Bu kayıt zaten mevcut."],
  [/foreign key/i, "İlişkili kayıtlar nedeniyle bu işlem yapılamaz."],
  [/check constraint/i, "Girilen bilgiler geçerli değil."],
];

export const GENEL_HATA = "Bir hata oluştu, lütfen tekrar deneyin.";

export function hataMesajiCoz(hata: { message?: string } | null | undefined): string {
  const mesaj = hata?.message ?? "";
  for (const [kod, metin] of Object.entries(KOD_MESAJLARI)) {
    if (mesaj === kod || mesaj.includes(kod)) return metin;
  }
  for (const [desen, metin] of IPUCLARI) {
    if (desen.test(mesaj)) return metin;
  }
  return GENEL_HATA;
}
