import {
  BarChart3,
  Banknote,
  BookOpen,
  Bot,
  Boxes,
  Building2,
  CalendarDays,
  CalendarOff,
  Coins,
  ClipboardList,
  CreditCard,
  DoorOpen,
  HandCoins,
  Landmark,
  Percent,
  History,
  LayoutDashboard,
  LifeBuoy,
  type LucideIcon,
  MessageCircle,
  MessageSquareWarning,
  Package,
  QrCode,
  ReceiptText,
  RefreshCw,
  ScanLine,
  Settings,
  ShieldCheck,
  Tablet,
  TrendingDown,
  UploadCloud,
  UserCog,
  Users,
  Wallet,
} from "lucide-react";

/**
 * Menü ikonları ADLA taşınır; bileşen referansı sunucudan istemciye geçirilemez. Hem sunucu sayfaları hem
 * istemci kabuğu bu haritayı kendi içinde çözer.
 */
export const MENU_IKONLARI = {
  panel: LayoutDashboard,
  "check-in": ScanLine,
  musteriler: Users,
  finans: Wallet,
  yonetim: Boxes,
  ayarlar: Settings,
  destek: LifeBuoy,
  kasa: Banknote,
  tahsilat: HandCoins,
  gider: TrendingDown,
  fatura: ReceiptText,
  "kredi-karti": CreditCard,
  rapor: BarChart3,
  paket: Package,
  denetim: History,
  ders: CalendarDays,
  program: ClipboardList,
  ekipman: DoorOpen,
  isletme: Building2,
  personel: UserCog,
  yetki: ShieldCheck,
  mesaj: MessageCircle,
  tablet: Tablet,
  qr: QrCode,
  arsiv: UploadCloud,
  senkron: RefreshCw,
  kilavuz: BookOpen,
  sohbet: Bot,
  talep: MessageSquareWarning,
  izin: CalendarOff,
  gelir: HandCoins,
  banka: Landmark,
  iskonto: Percent,
  hizmet: ClipboardList,
  hakedis: Coins,
} as const satisfies Record<string, LucideIcon>;

export type MenuIkonu = keyof typeof MENU_IKONLARI;
